[workspace]
members = ["client_dll", "server_dll", "common", "web_server", "clients_db", "overlay", "overlay_launcher"]

[profile.release]
#lto = true

[patch.crates-io]
#glium  = { git = 'https://github.com/qthree/glium.git' }
glium  = { path = 'D:\rust\glium' }
subprocess = { path = 'D:\rust\rust-subprocess'}