[package]
name = "fo_engine_functions"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen = "0.1"
dlopen_derive = "0.1"
once_cell = { version = "1.2" }
